<?php
/**
 * @file
 * f_delhi_panel_layout.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function f_delhi_panel_layout_ctools_plugin_api() {
  list($module, $api) = func_get_args();
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "panelizer" && $api == "panelizer") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "panels" && $api == "layouts") {
    return array("version" => "1");
  }
  list($module, $api) = func_get_args();
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_image_default_styles().
 */
function f_delhi_panel_layout_image_default_styles() {
  $styles = array();

  // Exported image style: constituency_image.
  $styles['constituency_image'] = array(
    'name' => 'constituency_image',
    'effects' => array(
      1 => array(
        'label' => 'Resize',
        'help' => 'Resizing will make images an exact set of dimensions. This may cause images to be stretched or shrunk disproportionately.',
        'effect callback' => 'image_resize_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_resize',
        'data' => array(
          'width' => '230',
          'height' => '150',
        ),
        'weight' => '1',
      ),
    ),
  );

  return $styles;
}
